apiVersion: apps/v1
kind: Deployment
metadata:
  name: content
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content
  template:
    metadata:
      labels:
        app: content
    spec:
      containers:
        - name: content
          image: keshox/content:7
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: content
spec:
  selector:
    app: content
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: content
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: codovstvo-test.ru
      http:
        paths:
          - backend:
              service:
                name: content
                port:
                  number: 80
            path: /content(/|$)(.*)
            pathType: Prefix
